name: todo
version: '3'

services:
  web:
    container_name: todo_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - .:/todo
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - todo-network
  db:
    container_name: todo_db
    image: postgres:13
    volumes:
      - .:/todo
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"
    networks:
      - todo-network

networks:
  todo-network:
    driver : bridge

    